### ISSUE TITLE
Date doesn't seem to be picking up host's time on 20.04 / latest when running in docker in docker.

### ISSUE THREAD

**Issue by wgillaspy** [tianon/docker-brew-ubuntu-core#184] opened 2020-07-25 23:50 UTC
This issue may be an edge case, but I use a docker in docker container to build my application images.  Some time in the last three days, the time seems to have stopped being aligned to the host time which manifested itself as "At least one invalid signature was encountered." when running apt-get update.  Using bionic instead of latest fixes the problem.

Description:
When running arm32v7/ubuntu:latest within a docker in docker container on a raspberry pi, the date/time doesn't seem be picking up from the host.  Oddly, when running arm32v7/ubuntu:latest (ie, not in the docker in docker container) directly on the raspberry pi it works fine.   The functionality last seemed to work on July 21.

- Raspberry Pi Ubuntu version:  Ubuntu 18.04.4 LTS
- Raspberry Pi docker version: Docker version 19.03.12, build 48a6621
- Docker in docker docker version: Docker version 19.03.12, build 48a6621

### Example:

**20.04** (doesn't work)
```
bash-5.0# docker run -it -e "TZ=America/New_York" arm32v7/ubuntu:latest bash
Unable to find image 'arm32v7/ubuntu:latest' locally
latest: Pulling from arm32v7/ubuntu
86924fd76ad7: Pull complete
8e967235e6ad: Pull complete
fabf100c8ea1: Pull complete
344cec738d22: Pull complete
Digest: sha256:6701deddfa3bdabb3a50eb0a24175367b9c7b145e8b2f889ee3b2c52a295ec0a
Status: Downloaded newer image for arm32v7/ubuntu:latest
root@0f1db66355b5:/# date
Sun Mar 15 05:22:31 America 1970
```

**18.04** (works)
```
bash-5.0# docker run -it -e "TZ=America/New_York" arm32v7/ubuntu:18.04 bash
Unable to find image 'arm32v7/ubuntu:18.04' locally
18.04: Pulling from arm32v7/ubuntu
de691405df56: Pull complete
e5a766b93ee2: Pull complete
8c97e104d736: Pull complete
d7a97b3bf2bf: Pull complete
Digest: sha256:8d8280314eac99b6ce1e5307d0093411150a8c09b59f390658952d50139c4722
Status: Downloaded newer image for arm32v7/ubuntu:18.04
root@b5d3f9235b07:/# date
Sat Jul 25 23:12:58 America 2020
```

**Comment by tianon** [comment] 2020-07-27 16:14
This has got to be related to #183 -- I bet if you try `apt-get update` you'll see similar errors to that issue (because I think the two are the same root cause).

**Comment by tianon** [comment] 2020-11-18 19:30
In other words, in order to resolve this, your host needs to have installed:

- Docker version 19.03.9 or newer
- libseccomp version 2.4.2 or newer

(Closing since this is not an issue we can fix in the image, but rather an issue that needs to be fixed on the host.)

**Closed by tianon** 2020-11-18 19:30 UTC
