### ISSUE TITLE
Device nodes in image layer

### ISSUE THREAD

**Issue by willmtemple** [tianon/docker-brew-ubuntu-core#62] opened 2016-08-08 16:01 UTC
On the current Ubuntu /dev is populated with several device nodes that shouldn't be necessary. This doesn't affect deployment using docker, but can affect other methods of consuming the image. However, docker doesn't use these nodes, as it mounts a tmpfs over /dev when the container runs, so the device nodes are discarded.

In my use case, I check the image layers out onto disk and commit them to an ostree, which doesn't handle device nodes, and so breaks on any ubuntu family image, or any image derived from ubuntu. I can work around this, but at the same time I'm not sure that having the device nodes in the image is necessary.

Is there a reason that they're required, or could the Dockerfiles just `rm -rf /dev/*`?

**Comment by tianon** [comment] 2016-08-08 16:22
Deleting them doesn't reclaim the space they take up and adds another layer to our image (since they'll be deleted in a new layer); adding to that the fact that Docker itself completely ignores them (making them harmless for the image's main use case) there doesn't seem to be a very strong reason for removing them at this level.  Additionally, it's worth noting that device nodes can be created anywhere in the filesystem, and Docker does provide the `mknod` capability, so applying this change would only supply a temporary workaround for the most common instance of your particular issue (which is likely better to apply directly to whatever process you have extracting the images -- purging `/dev` is totally sane if Docker is the source of the images given the way it treats `/dev` as a special case).

**Comment by justincormack** [comment] 2016-11-24 10:57
This came up again - the issue is that if you use Docker with user namespaces you cannot actually create device nodes at all (userns capabilities are restricted in some ways compared to full capabilities, and you cannot create device nodes at all). This makes these images unusable.

As far as I can see the solutions are to
1. purge in the build process
2. use 1.13 --squash in the build
3. change docker to ignore failure to create device nodes when unpacking

I do think that it is both incorrect for official images to contain device nodes, so we should work on removing them, and also worthwhile for Docker to fail gracefully, so will look at doing that too...

**Comment by justincormack** [comment] 2016-11-24 10:57
cc @jpetazzo

**Comment by tianon** [comment] 2016-11-28 20:12
@gaughen @OddBloke think there's any chance of getting `/dev` removed from the partner-images tarballs?  If Docker is the primary consumer of those, `/dev` has been mounted over for quite some time now (many, many versions), so it would be safe to do so. :smile:

**Comment by jpetazzo** [comment] 2016-11-28 20:39
Agreed with @justincormack; I guess we can work on both fixes.

"Be conservative in what you send, be liberal in what you accept." :)

**Comment by tianon** [comment] 2016-11-28 20:44
Talked with @gaughen offline and filed https://bugs.launchpad.net/cloud-images/+bug/1645468 downstream so they can track it easier. :+1:

**Comment by tianon** [comment] 2017-06-05 19:40
Closing this in favor of https://bugs.launchpad.net/cloud-images/+bug/1645468 since there's nothing more we can/should do here except wait for upstream to decide whether `/dev` can/should be removed from the tarballs they produce. :+1:

**Closed by tianon** 2017-06-05 19:40 UTC
