### ISSUE TITLE
Previously working docker build with ubuntu:14.04 started failing

### ISSUE THREAD

**Issue by chatsap** [tianon/docker-brew-ubuntu-core#100] opened 2017-09-20 15:53 UTC
Hi,

I am using ubuntu:14.04 image for my application docker build. It was working fine around one month back. When I tried it today after a month's time, it is failing with below error - 

```
Get:12 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [3997 B]
Get:13 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.1 kB]
Get:14 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [550 kB]
Get:15 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [15.5 kB]
Get:16 http://archive.ubuntu.com trusty-backports/main amd64 Packages [14.8 kB]
Get:17 http://archive.ubuntu.com trusty-backports/restricted amd64 Packages [40 B]
Get:18 http://archive.ubuntu.com trusty-backports/universe amd64 Packages [52.6 kB]
Get:19 http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1396 B]
Get:20 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:21 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:22 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:23 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Get:24 http://archive.ubuntu.com trusty/multiverse amd64 Packages [169 kB]
Fetched 21.0 MB in 9s (2201 kB/s)
W: GPG error: http://archive.ubuntu.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 16126D3A3E5C1192
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get -y install     software-properties-common     python-software-properties     debian-archive-keyring     wget     curl     vim     aptitude     dialog     net-tools     mcrypt     build-essential     tcl8.5     git' returned a non-zero code: 100
````

Here is how first few lines of my docker file looks like - 
```
# Pull from the ubuntu:14.04 image
FROM ubuntu:14.04


# Update cache and install base packages
RUN apt-get update && apt-get -y install \
    software-properties-common \
    python-software-properties \
    debian-archive-keyring \
    wget \
    curl \
    vim \
    aptitude \
    dialog \
    net-tools \
    mcrypt \
    build-essential \
    tcl8.5 \
    git

# Download Nginx signing key
RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com C300EE8C

# Add to repository sources list
RUN add-apt-repository ppa:nginx/stable

# Update cache and install Nginx
RUN apt-get update && apt-get -y install \
    nginx \
    php5-fpm \
    php5-cli \
    php5-pgsql \
    php5-curl \
    php5-mcrypt \
    php5-gd \
    php5-redis
```

By any chance is this issue related to this ticket - https://bugs.launchpad.net/cloud-images/+bug/1711735 ?

Any help will be appreciated.

**Comment by yosifkit** [comment] 2017-09-20 19:39
The Launchpad issue is about other architectures, not really just a bad cache.

Similar issues: https://github.com/docker-library/official-images/issues/1350, https://github.com/docker-library/openjdk/issues/90, https://github.com/docker-library/buildpack-deps/issues/40.

> In my personal experience, `Hash Sum mismatch` usually means one of the following:
>
> 1. temporary glitch in the mirror / CDN (or mis-generation of mirror files, in the case of non-Debian repositories)
> 2. temporary glitch in local network / firewall or route to mirror / CDN
> 3. glitch in APT cacher (flushing cache usually fixes this)
>
> Have you tried again to see if the issue resolved itself?
>
> \- https://github.com/docker-library/openjdk/issues/90#issuecomment-268863365

**Comment by chatsap** [comment] 2017-09-21 03:17
Tried below options based on @yosifkit 's reply.

1. Tried docker build today from my home ISP where it used to work before. No luck.

2. Flushed APT cache using below command 
`RUN apt-get clean`
and ran docker build with `--no-cache` option.

Still having the same issue.

**Comment by chatsap** [comment] 2017-09-21 07:32
Update:

Tried adding the key using `RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 16126D3A3E5C1192`

With this previous error is not occurring , but getting below error - 

```
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty-backports InRelease [65.9 kB]
Get:4 http://archive.ubuntu.com trusty Release.gpg [72 B]
Get:5 http://archive.ubuntu.com trusty Release [11.9 kB]
Get:6 http://security.ubuntu.com trusty-security/universe Sources [75.8 kB]
Get:7 http://archive.ubuntu.com trusty-updates/universe Sources [240 kB]
Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [828 kB]
Get:9 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1274 kB]
Get:10 http://security.ubuntu.com trusty-security/restricted amd64 Packages [17.8 kB]
Get:11 http://security.ubuntu.com trusty-security/universe amd64 Packages [237 kB]
Get:12 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.1 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [550 kB]
Get:14 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [3997 B]
Get:15 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [15.5 kB]
Get:16 http://archive.ubuntu.com trusty-backports/main amd64 Packages [14.8 kB]
Get:17 http://archive.ubuntu.com trusty-backports/restricted amd64 Packages [40 B]
Get:18 http://archive.ubuntu.com trusty-backports/universe amd64 Packages [52.6 kB]
Get:19 http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1396 B]
Fetched 3542 kB in 6s (580 kB/s)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release  Unable to find expected entry 'universe/source/Sources' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get -y install     software-properties-common     python-software-properties     debian-archive-keyring     wget     curl     vim     aptitude     dialog     net-tools     mcrypt     build-essential     tcl8.5     git' returned a non-zero code: 100
```

**Comment by yosifkit** [comment] 2017-09-21 22:30
I am unable to reproduce here, so it is still most likely an out-of-sync or misbehaving mirror closest to your location (which would cause both your work and home to fail).  As a side note, `apt cache clean` should not be needed since the base images do not contain any apt cache.  And these [lines](https://github.com/tianon/docker-brew-ubuntu-core/blob/31ebd22e9e83185d69d50b3492911aedf519dd4a/trusty/Dockerfile#L21-L24) ensure that the cache is always cleaned up.

Since this is not an issue with the image, I'll close the issue.

```console
$ docker run -it --rm ubuntu:14.04
root@2daddf1a0125:/# apt-get update
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty-backports InRelease [65.9 kB] 
Get:4 http://security.ubuntu.com trusty-security/universe Sources [75.8 kB]
Get:5 http://archive.ubuntu.com trusty Release.gpg [933 B]                     
Get:6 http://archive.ubuntu.com trusty Release [58.5 kB]                       
Get:7 http://security.ubuntu.com trusty-security/main amd64 Packages [830 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe Sources [240 kB]
Get:9 http://security.ubuntu.com trusty-security/restricted amd64 Packages [17.8 kB]
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [238 kB]
Get:11 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1274 kB]
Get:12 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.1 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [550 kB]
Get:14 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [3997 B]
Get:15 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [15.5 kB]
Get:16 http://archive.ubuntu.com trusty-backports/main amd64 Packages [14.8 kB]
Get:17 http://archive.ubuntu.com trusty-backports/restricted amd64 Packages [40 B]
Get:18 http://archive.ubuntu.com trusty-backports/universe amd64 Packages [52.6 kB]
Get:19 http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1396 B]
Get:20 http://archive.ubuntu.com trusty/universe Sources [7926 kB]             
Get:21 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]          
Get:22 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]    
Get:23 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]      
Get:24 http://archive.ubuntu.com trusty/multiverse amd64 Packages [169 kB]     
Fetched 21.0 MB in 2min 0s (175 kB/s)                                          
Reading package lists... Done
root@2daddf1a0125:/#
```

**Closed by yosifkit** 2017-09-21 22:30 UTC
