### ISSUE TITLE
Image becomes unusable once certain apt-get packages are install

### ISSUE THREAD

**Issue by mikekberg** [tianon/docker-brew-ubuntu-core#140] opened 2018-11-20 19:53 UTC
Steps to Reproduce:

Running on a QNAP Arm NAS

Dockerfile:
```
FROM arm32v7/ubuntu

RUN apt-get update \
    && apt-get install -y git
```

1. Build above docker file
2. docker run --rm -it <container id>
3. Observe the error:
'container-station/docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory".'

4. Remove the `&& apt-get install git` from the docker file
5. Build the new image
6. Run the command from step 2
7. Observe the image works as expected.

**Comment by mwhudson** [comment] 2018-11-20 20:52
That's, um, unexpected. Which model of NAS is it? It's not armv6 or something like that? Otherwise, I don't know how I can help debug this unfortunately.

**Comment by tianon** [comment] 2018-12-31 18:57
Closing -- unable to reproduce (problem appears to be environmental).

**Closed by tianon** 2018-12-31 18:57 UTC
