### ISSUE TITLE
where are the commands: ip and ifconfig in 16.04 ?

### ISSUE THREAD

**Issue by MrMic** [tianon/docker-brew-ubuntu-core#63] opened 2016-08-19 13:32 UTC
All is in the  title.

**Comment by yosifkit** [comment] 2016-08-19 21:55
The set of installed packages is controlled by Canonical in the tar files they generate for the "minimal set of packages that can be called Ubuntu": https://partner-images.canonical.com/core/ and we only [add a few tweaks](https://github.com/tianon/docker-brew-ubuntu-core/blob/3485528d76452eff9e7d3b3f222bd21a966659a5/xenial/Dockerfile#L4-L40) to the docker images.

**Comment by tianon** [comment] 2016-08-26 23:09
Aha, https://bugs.launchpad.net/cloud-images/+bug/1567349 seems to be referring to this exact issue.

**Comment by tianon** [comment] 2016-08-26 23:18
Given that this is by design (and tracked upstream), I'm closing.  I'd suggest subscribing to the upstream bug (or creating a short `Dockerfile` installing the utilities you're interested in) for further updates. :+1:

**Closed by tianon** 2016-08-26 23:18 UTC
