### ISSUE TITLE
apt-get update of ubuntu 14.04.2 fails due to GPG key error

### ISSUE THREAD

**Issue by assaflavie** [tianon/docker-brew-ubuntu-core#36] opened 2015-08-12 09:32 UTC
The following:

```
docker pull ubuntu:14.04.2
docker run -it ubuntu:14.04.2
$ apt-get update
```

fails with the following error:

```
...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 16126D3A3E5C1192

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

[EDIT]

I should mention this happens on OSX with Boot2docker 1.8. For some reason I cannot recreate this on Linux. Things I've tried: upgrading boot2docker (which starts with a fresh ISO image, no docker images).

**Comment by zakin** [comment] 2015-09-02 18:45
Adding the solution here, in case someone else runs into this:

Thanks to Assaf Lavie for pointing this out and figuring out the cause - Improper caching by ISP causes issue.

Reran through different connection, works perfectly.

**Comment by assaflavie** [comment] 2015-09-02 18:48
Yea, pretty amazing how lame ISPs can be.
Actual credit for figuring this out belongs to Ruby Feinstein (@shoote).

**Comment by tianon** [comment] 2015-09-02 20:19
Ugh, this is definitely irritating.  I hate `https` APT repos, but avoiding ISPs being silly seems like a pretty decent reason to consider them.

Mind if we close this since it's not really an issue with the image? (certainly not something we can fix)

**Comment by assaflavie** [comment] 2015-09-03 04:19
Sure.

**Comment by tianon** [comment] 2015-09-04 00:55
Thanks :+1: :heart:

**Closed by tianon** 2015-09-04 00:55 UTC

**Comment by droidlabour** [comment] 2016-03-16 12:23
Thanks (Y)
